# Generated by Django 5.2 on 2025-05-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
