# Generated by Django 5.2 on 2025-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
