# Generated by Django 5.2 on 2025-05-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_account_id_log_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
        migrations.RenameField(
            model_name='log',
            old_name='account',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='log',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', on_delete=django.db.models.deletion.CASCADE, to='core.destination'),
        ),
        migrations.RenameField(
            model_name='log',
            old_name='destination',
            new_name='destination_id',
        ),
    ]
